"""
QPX_CREATE_TEMPLATE_ENGINE.py

Sprint 5
Milestone 3

Creates the Template Engine and default templates.
"""

from pathlib import Path

ROOT = Path(__file__).parent


def write(relative_path, contents):
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents.strip() + "\n", encoding="utf-8")
    print(f"Created: {relative_path}")


print("=" * 60)
print("QPX_ALPHA Template Engine")
print("=" * 60)

# ---------------------------------------------------------------------
# Template Engine
# ---------------------------------------------------------------------

write(
    "tools/template_engine.py",
'''
"""
Template Engine

Loads reusable templates from tools/templates.
"""

from pathlib import Path


class TemplateEngine:

    def __init__(self):
        self.template_dir = (
            Path(__file__).parent / "templates"
        )

    def load(self, template_name):

        path = self.template_dir / template_name

        if not path.exists():
            raise FileNotFoundError(template_name)

        return path.read_text(encoding="utf-8")

    def render(self, template_name, **kwargs):

        text = self.load(template_name)

        for key, value in kwargs.items():
            text = text.replace("{{" + key + "}}", str(value))

        return text
'''
)

# ---------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------

write(
    "tools/templates/module.tpl",
'''
"""
{{NAME}} Module
Generated by QPX_ALPHA
"""

class {{NAME}}:
    pass
'''
)

write(
    "tools/templates/service.tpl",
'''
"""
{{NAME}} Service
Generated by QPX_ALPHA
"""

class {{NAME}}Service:
    pass
'''
)

write(
    "tools/templates/test.tpl",
'''
def test_{{LOWER}}():
    print("PASS")
'''
)

write(
    "tools/templates/readme.tpl",
'''
# {{NAME}}

Generated by QPX_ALPHA.
'''
)

write(
    "tools/templates/config.tpl",
'''
# Configuration

name={{NAME}}
'''
)

# ---------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------

write(
    "tests/test_template_engine.py",
'''
from tools.template_engine import TemplateEngine

engine = TemplateEngine()

text = engine.render(
    "module.tpl",
    NAME="Example"
)

assert "Example" in text

print("Template Engine PASS")
'''
)

print()
print("=" * 60)
print("SPRINT 5 MILESTONE 3 COMPLETE")
print("=" * 60)
print("Created:")
print("  tools/template_engine.py")
print("  tools/templates/*.tpl")
print("  tests/test_template_engine.py")
print("=" * 60)