#!/usr/bin/env python3
"""Recover failed V1/V2 installs and complete QPX walk-forward validation."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
import shutil
import subprocess
import sys
import textwrap


def find_root() -> Path:
    for start in (
        Path(__file__).resolve().parent,
        Path.cwd().resolve(),
    ):
        for candidate in (start, *start.parents):
            if (
                (candidate / ".git").exists()
                and (candidate / "qpx_bot").exists()
                and (candidate / "tests").exists()
            ):
                return candidate

    raise RuntimeError(
        "QPX_ALPHA was not found. Save this installer inside "
        "/storage/emulated/0/QPX_ALPHA and run it again."
    )


ROOT = find_root()
STAMP = datetime.now().strftime("%Y%m%d_%H%M%S")
BACKUP = ROOT / "backups" / "qpx_walk_forward_v3" / STAMP

FILES = {'qpx_bot/__init__.py': '"""\n'
                        'QPX Bot\n'
                        '\n'
                        'Backtesting bot for the Hybrid Dividend + Swing strategy.\n'
                        '"""\n'
                        '\n'
                        '__version__ = "1.8.0"\n',
 'qpx_bot/performance.py': '"""Contribution-adjusted performance and benchmark analytics."""\n'
                           '\n'
                           'from __future__ import annotations\n'
                           '\n'
                           'import csv\n'
                           'from dataclasses import dataclass\n'
                           'from datetime import date, datetime, timezone\n'
                           'from math import prod, sqrt\n'
                           'from pathlib import Path\n'
                           'from statistics import fmean, stdev\n'
                           'from typing import Iterable, Sequence\n'
                           '\n'
                           'from qpx_bot.config import BotConfig\n'
                           'from qpx_bot.hybrid import HybridBacktestResult\n'
                           '\n'
                           '\n'
                           'TRADING_DAYS_PER_YEAR = 252\n'
                           '\n'
                           '\n'
                           '@dataclass(frozen=True, slots=True)\n'
                           'class ReturnMetrics:\n'
                           '    observation_count: int\n'
                           '    total_return: float\n'
                           '    cagr: float\n'
                           '    annualized_volatility: float\n'
                           '    sharpe_ratio: float\n'
                           '    sortino_ratio: float\n'
                           '    maximum_drawdown: float\n'
                           '    exposure: float\n'
                           '\n'
                           '\n'
                           '@dataclass(frozen=True, slots=True)\n'
                           'class AdjustedBar:\n'
                           '    date: date\n'
                           '    open: float\n'
                           '    close: float\n'
                           '    adjusted_close: float\n'
                           '\n'
                           '    @property\n'
                           '    def adjustment_factor(self) -> float:\n'
                           '        if self.close <= 0:\n'
                           '            raise ValueError("Benchmark close must be positive.")\n'
                           '        return self.adjusted_close / self.close\n'
                           '\n'
                           '    @property\n'
                           '    def adjusted_open(self) -> float:\n'
                           '        return self.open * self.adjustment_factor\n'
                           '\n'
                           '\n'
                           '@dataclass(frozen=True, slots=True)\n'
                           'class BenchmarkPoint:\n'
                           '    date: date\n'
                           '    equity: float\n'
                           '    total_contributions: float\n'
                           '\n'
                           '\n'
                           '@dataclass(frozen=True, slots=True)\n'
                           'class BenchmarkResult:\n'
                           '    symbol: str\n'
                           '    starting_cash: float\n'
                           '    total_contributions: float\n'
                           '    ending_equity: float\n'
                           '    points: tuple[BenchmarkPoint, ...]\n'
                           '    returns: tuple[float, ...]\n'
                           '    metrics: ReturnMetrics\n'
                           '    uses_adjusted_close: bool\n'
                           '\n'
                           '\n'
                           'def _parse_date(raw_value: str) -> date:\n'
                           '    value = str(raw_value).strip()\n'
                           '\n'
                           '    try:\n'
                           '        numeric = float(value)\n'
                           '    except ValueError:\n'
                           '        numeric = None\n'
                           '\n'
                           '    if numeric is not None:\n'
                           '        if numeric > 10_000_000_000:\n'
                           '            numeric /= 1000.0\n'
                           '        return datetime.fromtimestamp(\n'
                           '            numeric,\n'
                           '            tz=timezone.utc,\n'
                           '        ).date()\n'
                           '\n'
                           '    try:\n'
                           '        return datetime.fromisoformat(\n'
                           '            value.replace("Z", "+00:00")\n'
                           '        ).date()\n'
                           '    except ValueError:\n'
                           '        pass\n'
                           '\n'
                           '    for date_format in (\n'
                           '        "%Y-%m-%d",\n'
                           '        "%Y/%m/%d",\n'
                           '        "%m/%d/%Y",\n'
                           '        "%d/%m/%Y",\n'
                           '    ):\n'
                           '        try:\n'
                           '            return datetime.strptime(value, date_format).date()\n'
                           '        except ValueError:\n'
                           '            continue\n'
                           '\n'
                           '    raise ValueError(f"Unsupported benchmark date: {raw_value!r}")\n'
                           '\n'
                           '\n'
                           'def load_adjusted_bars(\n'
                           '    filename: str | Path,\n'
                           ') -> tuple[list[AdjustedBar], bool]:\n'
                           '    """\n'
                           '    Load benchmark bars from SWING.csv.\n'
                           '\n'
                           '    AdjClose is preferred because it incorporates distributions and\n'
                           '    splits. Close is used only as a transparent price-return '
                           'fallback.\n'
                           '    """\n'
                           '    path = Path(filename).expanduser().resolve()\n'
                           '\n'
                           '    with path.open(\n'
                           '        "r",\n'
                           '        newline="",\n'
                           '        encoding="utf-8-sig",\n'
                           '    ) as file:\n'
                           '        reader = csv.DictReader(file)\n'
                           '\n'
                           '        if not reader.fieldnames:\n'
                           '            raise ValueError("Benchmark CSV does not contain a '
                           'header.")\n'
                           '\n'
                           '        headers = {\n'
                           '            header.strip().lower(): header\n'
                           '            for header in reader.fieldnames\n'
                           '        }\n'
                           '\n'
                           '        def column(*names: str) -> str:\n'
                           '            for name in names:\n'
                           '                if name in headers:\n'
                           '                    return headers[name]\n'
                           '            raise ValueError(\n'
                           '                "Benchmark CSV is missing one of: "\n'
                           '                + ", ".join(names)\n'
                           '            )\n'
                           '\n'
                           '        date_column = column(\n'
                           '            "date",\n'
                           '            "time",\n'
                           '            "datetime",\n'
                           '            "timestamp",\n'
                           '        )\n'
                           '        open_column = column("open")\n'
                           '        close_column = column(\n'
                           '            "close",\n'
                           '            "adj close",\n'
                           '            "adjusted close",\n'
                           '        )\n'
                           '        adjusted_column = None\n'
                           '\n'
                           '        for candidate in (\n'
                           '            "adjclose",\n'
                           '            "adj close",\n'
                           '            "adjusted close",\n'
                           '        ):\n'
                           '            if candidate in headers:\n'
                           '                adjusted_column = headers[candidate]\n'
                           '                break\n'
                           '\n'
                           '        uses_adjusted = adjusted_column is not None\n'
                           '        bars: list[AdjustedBar] = []\n'
                           '\n'
                           '        for line_number, row in enumerate(reader, start=2):\n'
                           '            try:\n'
                           '                close = float(row[close_column])\n'
                           '                adjusted = (\n'
                           '                    float(row[adjusted_column])\n'
                           '                    if adjusted_column is not None\n'
                           '                    else close\n'
                           '                )\n'
                           '                bar = AdjustedBar(\n'
                           '                    date=_parse_date(row[date_column]),\n'
                           '                    open=float(row[open_column]),\n'
                           '                    close=close,\n'
                           '                    adjusted_close=adjusted,\n'
                           '                )\n'
                           '\n'
                           '                if (\n'
                           '                    bar.open <= 0\n'
                           '                    or bar.close <= 0\n'
                           '                    or bar.adjusted_close <= 0\n'
                           '                ):\n'
                           '                    raise ValueError(\n'
                           '                        "benchmark prices must be positive"\n'
                           '                    )\n'
                           '\n'
                           '                bars.append(bar)\n'
                           '            except (TypeError, ValueError, KeyError) as exc:\n'
                           '                raise ValueError(\n'
                           '                    f"Invalid benchmark row {line_number}: {exc}"\n'
                           '                ) from exc\n'
                           '\n'
                           '    bars.sort(key=lambda bar: bar.date)\n'
                           '    dates = [bar.date for bar in bars]\n'
                           '\n'
                           '    if not bars:\n'
                           '        raise ValueError("Benchmark CSV contains no rows.")\n'
                           '\n'
                           '    if len(dates) != len(set(dates)):\n'
                           '        raise ValueError("Benchmark CSV contains duplicate dates.")\n'
                           '\n'
                           '    return bars, uses_adjusted\n'
                           '\n'
                           '\n'
                           'def metrics_from_returns(\n'
                           '    returns: Sequence[float],\n'
                           '    *,\n'
                           '    exposure: float = 0.0,\n'
                           ') -> ReturnMetrics:\n'
                           '    cleaned = [\n'
                           '        float(value)\n'
                           '        for value in returns\n'
                           '        if value > -1.0\n'
                           '    ]\n'
                           '\n'
                           '    if not cleaned:\n'
                           '        return ReturnMetrics(\n'
                           '            observation_count=0,\n'
                           '            total_return=0.0,\n'
                           '            cagr=0.0,\n'
                           '            annualized_volatility=0.0,\n'
                           '            sharpe_ratio=0.0,\n'
                           '            sortino_ratio=0.0,\n'
                           '            maximum_drawdown=0.0,\n'
                           '            exposure=max(0.0, min(1.0, exposure)),\n'
                           '        )\n'
                           '\n'
                           '    wealth = 1.0\n'
                           '    peak = 1.0\n'
                           '    maximum_drawdown = 0.0\n'
                           '\n'
                           '    for value in cleaned:\n'
                           '        wealth *= 1.0 + value\n'
                           '        peak = max(peak, wealth)\n'
                           '\n'
                           '        if peak > 0:\n'
                           '            maximum_drawdown = max(\n'
                           '                maximum_drawdown,\n'
                           '                (peak - wealth) / peak,\n'
                           '            )\n'
                           '\n'
                           '    total_return = wealth - 1.0\n'
                           '    years = len(cleaned) / TRADING_DAYS_PER_YEAR\n'
                           '    cagr = (\n'
                           '        wealth ** (1.0 / years) - 1.0\n'
                           '        if wealth > 0 and years > 0\n'
                           '        else -1.0\n'
                           '    )\n'
                           '\n'
                           '    average = fmean(cleaned)\n'
                           '    volatility = (\n'
                           '        stdev(cleaned) * sqrt(TRADING_DAYS_PER_YEAR)\n'
                           '        if len(cleaned) > 1\n'
                           '        else 0.0\n'
                           '    )\n'
                           '    daily_deviation = (\n'
                           '        stdev(cleaned)\n'
                           '        if len(cleaned) > 1\n'
                           '        else 0.0\n'
                           '    )\n'
                           '    sharpe = (\n'
                           '        average / daily_deviation\n'
                           '        * sqrt(TRADING_DAYS_PER_YEAR)\n'
                           '        if daily_deviation > 0\n'
                           '        else 0.0\n'
                           '    )\n'
                           '\n'
                           '    downside_squared = [\n'
                           '        min(0.0, value) ** 2\n'
                           '        for value in cleaned\n'
                           '    ]\n'
                           '    downside_deviation = sqrt(fmean(downside_squared))\n'
                           '    sortino = (\n'
                           '        average / downside_deviation\n'
                           '        * sqrt(TRADING_DAYS_PER_YEAR)\n'
                           '        if downside_deviation > 0\n'
                           '        else 0.0\n'
                           '    )\n'
                           '\n'
                           '    return ReturnMetrics(\n'
                           '        observation_count=len(cleaned),\n'
                           '        total_return=total_return,\n'
                           '        cagr=cagr,\n'
                           '        annualized_volatility=volatility,\n'
                           '        sharpe_ratio=sharpe,\n'
                           '        sortino_ratio=sortino,\n'
                           '        maximum_drawdown=maximum_drawdown,\n'
                           '        exposure=max(0.0, min(1.0, exposure)),\n'
                           '    )\n'
                           '\n'
                           '\n'
                           'def hybrid_flow_adjusted_returns(\n'
                           '    result: HybridBacktestResult,\n'
                           ') -> tuple[float, ...]:\n'
                           '    """Remove external deposits before calculating daily returns."""\n'
                           '    returns: list[float] = []\n'
                           '    previous_equity = result.starting_cash\n'
                           '    previous_contributions = result.starting_cash\n'
                           '\n'
                           '    for point in result.equity_curve:\n'
                           '        contribution = (\n'
                           '            point.total_contributions\n'
                           '            - previous_contributions\n'
                           '        )\n'
                           '\n'
                           '        if previous_equity <= 0:\n'
                           '            daily_return = 0.0\n'
                           '        else:\n'
                           '            daily_return = (\n'
                           '                point.total_equity\n'
                           '                - contribution\n'
                           '            ) / previous_equity - 1.0\n'
                           '\n'
                           '        returns.append(daily_return)\n'
                           '        previous_equity = point.total_equity\n'
                           '        previous_contributions = point.total_contributions\n'
                           '\n'
                           '    return tuple(returns)\n'
                           '\n'
                           '\n'
                           'def hybrid_metrics(\n'
                           '    result: HybridBacktestResult,\n'
                           ') -> tuple[ReturnMetrics, tuple[float, ...]]:\n'
                           '    returns = hybrid_flow_adjusted_returns(result)\n'
                           '    exposure = (\n'
                           '        sum(\n'
                           '            1\n'
                           '            for point in result.equity_curve\n'
                           '            if point.swing_market_value > 0\n'
                           '        )\n'
                           '        / len(result.equity_curve)\n'
                           '        if result.equity_curve\n'
                           '        else 0.0\n'
                           '    )\n'
                           '    return (\n'
                           '        metrics_from_returns(returns, exposure=exposure),\n'
                           '        returns,\n'
                           '    )\n'
                           '\n'
                           '\n'
                           'def run_buy_and_hold_benchmark(\n'
                           '    *,\n'
                           '    bars: Sequence[AdjustedBar],\n'
                           '    symbol: str,\n'
                           '    config: BotConfig,\n'
                           '    uses_adjusted_close: bool = True,\n'
                           ') -> BenchmarkResult:\n'
                           '    """Fractional-share buy-and-hold with matching monthly '
                           'deposits."""\n'
                           '    config.validate()\n'
                           '\n'
                           '    if not bars:\n'
                           '        raise ValueError("Benchmark bars cannot be empty.")\n'
                           '\n'
                           '    shares = 0.0\n'
                           '    total_contributions = config.starting_cash\n'
                           '    cash_to_invest = config.starting_cash\n'
                           '    points: list[BenchmarkPoint] = []\n'
                           '    previous_month = (\n'
                           '        bars[0].date.year,\n'
                           '        bars[0].date.month,\n'
                           '    )\n'
                           '\n'
                           '    for index, bar in enumerate(bars):\n'
                           '        current_month = (bar.date.year, bar.date.month)\n'
                           '\n'
                           '        if index > 0 and current_month != previous_month:\n'
                           '            cash_to_invest += config.monthly_contribution\n'
                           '            total_contributions += config.monthly_contribution\n'
                           '            previous_month = current_month\n'
                           '\n'
                           '        if cash_to_invest > 0:\n'
                           '            fill = (\n'
                           '                bar.adjusted_open\n'
                           '                * (1.0 + config.slippage_rate)\n'
                           '            )\n'
                           '            shares += cash_to_invest / fill\n'
                           '            cash_to_invest = 0.0\n'
                           '\n'
                           '        points.append(\n'
                           '            BenchmarkPoint(\n'
                           '                date=bar.date,\n'
                           '                equity=shares * bar.adjusted_close,\n'
                           '                total_contributions=total_contributions,\n'
                           '            )\n'
                           '        )\n'
                           '\n'
                           '    returns: list[float] = []\n'
                           '    previous_equity = config.starting_cash\n'
                           '    previous_contributions = config.starting_cash\n'
                           '\n'
                           '    for point in points:\n'
                           '        contribution = (\n'
                           '            point.total_contributions\n'
                           '            - previous_contributions\n'
                           '        )\n'
                           '        daily_return = (\n'
                           '            (point.equity - contribution) / previous_equity - 1.0\n'
                           '            if previous_equity > 0\n'
                           '            else 0.0\n'
                           '        )\n'
                           '        returns.append(daily_return)\n'
                           '        previous_equity = point.equity\n'
                           '        previous_contributions = point.total_contributions\n'
                           '\n'
                           '    metrics = metrics_from_returns(\n'
                           '        returns,\n'
                           '        exposure=1.0,\n'
                           '    )\n'
                           '\n'
                           '    return BenchmarkResult(\n'
                           '        symbol=symbol.strip().upper(),\n'
                           '        starting_cash=config.starting_cash,\n'
                           '        total_contributions=total_contributions,\n'
                           '        ending_equity=points[-1].equity,\n'
                           '        points=tuple(points),\n'
                           '        returns=tuple(returns),\n'
                           '        metrics=metrics,\n'
                           '        uses_adjusted_close=uses_adjusted_close,\n'
                           '    )\n',
 'qpx_bot/walk_forward.py': '"""Rolling walk-forward validation for QPX Bot."""\n'
                            '\n'
                            'from __future__ import annotations\n'
                            '\n'
                            'import csv\n'
                            'import json\n'
                            'from dataclasses import asdict, dataclass, replace\n'
                            'from datetime import date\n'
                            'from pathlib import Path\n'
                            'from typing import Sequence\n'
                            '\n'
                            'from qpx_bot.config import BotConfig\n'
                            'from qpx_bot.data_loader import Candle\n'
                            'from qpx_bot.dividends import DividendEvent\n'
                            'from qpx_bot.hybrid import HybridBacktestResult, run_hybrid_backtest\n'
                            'from qpx_bot.performance import (\n'
                            '    AdjustedBar,\n'
                            '    BenchmarkResult,\n'
                            '    ReturnMetrics,\n'
                            '    hybrid_metrics,\n'
                            '    metrics_from_returns,\n'
                            '    run_buy_and_hold_benchmark,\n'
                            ')\n'
                            '\n'
                            '\n'
                            '@dataclass(frozen=True, slots=True)\n'
                            'class Candidate:\n'
                            '    name: str\n'
                            '    maximum_vix_for_entries: float\n'
                            '    breakout_volume_multiplier: float\n'
                            '\n'
                            '\n'
                            '@dataclass(frozen=True, slots=True)\n'
                            'class WalkForwardWindow:\n'
                            '    number: int\n'
                            '    train_start: date\n'
                            '    train_end: date\n'
                            '    test_start: date\n'
                            '    test_end: date\n'
                            '    selected_candidate: str\n'
                            '    selected_maximum_vix: float\n'
                            '    selected_breakout_volume: float\n'
                            '    training_score: float\n'
                            '    strategy_metrics: ReturnMetrics\n'
                            '    benchmark_metrics: ReturnMetrics\n'
                            '    strategy_trades: int\n'
                            '    strategy_win_rate: float\n'
                            '    strategy_profit_factor: float\n'
                            '    cagr_advantage: float\n'
                            '\n'
                            '\n'
                            '@dataclass(frozen=True, slots=True)\n'
                            'class WalkForwardResult:\n'
                            '    symbol: str\n'
                            '    train_bars: int\n'
                            '    test_bars: int\n'
                            '    step_bars: int\n'
                            '    windows: tuple[WalkForwardWindow, ...]\n'
                            '    out_of_sample_metrics: ReturnMetrics\n'
                            '    benchmark_metrics: ReturnMetrics\n'
                            '    cagr_advantage: float\n'
                            '    positive_alpha_windows: int\n'
                            '    total_windows: int\n'
                            '    benchmark_uses_adjusted_close: bool\n'
                            '\n'
                            '\n'
                            'def default_candidates(\n'
                            '    config: BotConfig,\n'
                            ') -> tuple[Candidate, ...]:\n'
                            '    """A small, declared grid to limit parameter-selection bias."""\n'
                            '    values = (\n'
                            '        max(18.0, config.maximum_vix_for_entries - 4.0),\n'
                            '        config.maximum_vix_for_entries,\n'
                            '        config.maximum_vix_for_entries + 4.0,\n'
                            '    )\n'
                            '    unique = tuple(dict.fromkeys(values))\n'
                            '\n'
                            '    return tuple(\n'
                            '        Candidate(\n'
                            '            name=f"VIX_{value:g}",\n'
                            '            maximum_vix_for_entries=value,\n'
                            '            breakout_volume_multiplier=(\n'
                            '                config.breakout_volume_multiplier\n'
                            '            ),\n'
                            '        )\n'
                            '        for value in unique\n'
                            '    )\n'
                            '\n'
                            '\n'
                            'def _candidate_config(\n'
                            '    base: BotConfig,\n'
                            '    candidate: Candidate,\n'
                            ') -> BotConfig:\n'
                            '    return replace(\n'
                            '        base,\n'
                            '        maximum_vix_for_entries=(\n'
                            '            candidate.maximum_vix_for_entries\n'
                            '        ),\n'
                            '        breakout_volume_multiplier=(\n'
                            '            candidate.breakout_volume_multiplier\n'
                            '        ),\n'
                            '    )\n'
                            '\n'
                            '\n'
                            'def _segment_result(\n'
                            '    *,\n'
                            '    swing_candles: Sequence[Candle],\n'
                            '    income_candles: Sequence[Candle],\n'
                            '    dividends: Sequence[DividendEvent],\n'
                            '    vix_values: Sequence[float],\n'
                            '    symbol: str,\n'
                            '    config: BotConfig,\n'
                            '    start_index: int,\n'
                            '    end_index: int,\n'
                            ') -> HybridBacktestResult:\n'
                            '    warmup = max(\n'
                            '        config.sma_trend_period\n'
                            '        + config.sma_slope_lookback\n'
                            '        + 2,\n'
                            '        config.ema_slow_period + 2,\n'
                            '        config.atr_period + 2,\n'
                            '        config.breakout_lookback + 2,\n'
                            '    )\n'
                            '    context_start = max(0, start_index - warmup)\n'
                            '    context_candles = swing_candles[\n'
                            '        context_start:end_index\n'
                            '    ]\n'
                            '    context_vix = vix_values[context_start:end_index]\n'
                            '    local_start = start_index - context_start\n'
                            '    segment_end_date = swing_candles[end_index - 1].date\n'
                            '    eligible_income = [\n'
                            '        candle\n'
                            '        for candle in income_candles\n'
                            '        if candle.date <= segment_end_date\n'
                            '    ]\n'
                            '\n'
                            '    return run_hybrid_backtest(\n'
                            '        swing_candles=context_candles,\n'
                            '        income_candles=eligible_income,\n'
                            '        dividends=dividends,\n'
                            '        swing_symbol=symbol,\n'
                            '        config=config,\n'
                            '        vix=context_vix,\n'
                            '        start_trading_index=local_start,\n'
                            '    )\n'
                            '\n'
                            '\n'
                            'def _training_score(metrics: ReturnMetrics) -> float:\n'
                            '    """Return-over-drawdown score calculated on training data '
                            'only."""\n'
                            '    return (\n'
                            '        metrics.cagr\n'
                            '        - (0.75 * metrics.maximum_drawdown)\n'
                            '    )\n'
                            '\n'
                            '\n'
                            'def run_walk_forward(\n'
                            '    *,\n'
                            '    swing_candles: Sequence[Candle],\n'
                            '    income_candles: Sequence[Candle],\n'
                            '    dividends: Sequence[DividendEvent],\n'
                            '    vix_values: Sequence[float],\n'
                            '    adjusted_bars: Sequence[AdjustedBar],\n'
                            '    symbol: str,\n'
                            '    config: BotConfig,\n'
                            '    train_bars: int = 252,\n'
                            '    test_bars: int = 63,\n'
                            '    step_bars: int = 63,\n'
                            '    candidates: Sequence[Candidate] | None = None,\n'
                            '    benchmark_uses_adjusted_close: bool = True,\n'
                            ') -> WalkForwardResult:\n'
                            '    """\n'
                            '    Select parameters on each rolling training window, then evaluate\n'
                            '    them once on the immediately following unseen test window.\n'
                            '    """\n'
                            '    config.validate()\n'
                            '\n'
                            '    if not (\n'
                            '        len(swing_candles)\n'
                            '        == len(vix_values)\n'
                            '    ):\n'
                            '        raise ValueError(\n'
                            '            "Swing candles and aligned VIX values must match."\n'
                            '        )\n'
                            '\n'
                            '    if train_bars < 2 or test_bars < 2 or step_bars < 1:\n'
                            '        raise ValueError(\n'
                            '            "Train/test windows must be at least two bars and "\n'
                            '            "step size must be positive."\n'
                            '        )\n'
                            '\n'
                            '    required = train_bars + test_bars\n'
                            '\n'
                            '    if len(swing_candles) < required:\n'
                            '        raise ValueError(\n'
                            '            f"Walk-forward requires at least {required} swing bars; '
                            '"\n'
                            '            f"only {len(swing_candles)} are available."\n'
                            '        )\n'
                            '\n'
                            '    candidate_list = tuple(\n'
                            '        candidates or default_candidates(config)\n'
                            '    )\n'
                            '\n'
                            '    if not candidate_list:\n'
                            '        raise ValueError("At least one candidate is required.")\n'
                            '\n'
                            '    adjusted_map = {\n'
                            '        bar.date: bar\n'
                            '        for bar in adjusted_bars\n'
                            '    }\n'
                            '    windows: list[WalkForwardWindow] = []\n'
                            '    all_strategy_returns: list[float] = []\n'
                            '    all_benchmark_returns: list[float] = []\n'
                            '    exposure_weighted = 0.0\n'
                            '    benchmark_exposure_weighted = 0.0\n'
                            '    total_observations = 0\n'
                            '    train_start = 0\n'
                            '    window_number = 1\n'
                            '\n'
                            '    while True:\n'
                            '        train_end = train_start + train_bars\n'
                            '        test_start = train_end\n'
                            '        test_end = test_start + test_bars\n'
                            '\n'
                            '        if test_end > len(swing_candles):\n'
                            '            break\n'
                            '\n'
                            '        scored: list[\n'
                            '            tuple[\n'
                            '                float,\n'
                            '                Candidate,\n'
                            '                BotConfig,\n'
                            '                ReturnMetrics,\n'
                            '            ]\n'
                            '        ] = []\n'
                            '\n'
                            '        for candidate in candidate_list:\n'
                            '            candidate_config = _candidate_config(\n'
                            '                config,\n'
                            '                candidate,\n'
                            '            )\n'
                            '            training_result = _segment_result(\n'
                            '                swing_candles=swing_candles,\n'
                            '                income_candles=income_candles,\n'
                            '                dividends=dividends,\n'
                            '                vix_values=vix_values,\n'
                            '                symbol=symbol,\n'
                            '                config=candidate_config,\n'
                            '                start_index=train_start,\n'
                            '                end_index=train_end,\n'
                            '            )\n'
                            '            training_metrics, _ = hybrid_metrics(\n'
                            '                training_result\n'
                            '            )\n'
                            '            scored.append(\n'
                            '                (\n'
                            '                    _training_score(training_metrics),\n'
                            '                    candidate,\n'
                            '                    candidate_config,\n'
                            '                    training_metrics,\n'
                            '                )\n'
                            '            )\n'
                            '\n'
                            '        scored.sort(\n'
                            '            key=lambda item: (\n'
                            '                item[0],\n'
                            '                item[3].cagr,\n'
                            '                -item[3].maximum_drawdown,\n'
                            '            ),\n'
                            '            reverse=True,\n'
                            '        )\n'
                            '        (\n'
                            '            best_score,\n'
                            '            best_candidate,\n'
                            '            selected_config,\n'
                            '            _,\n'
                            '        ) = scored[0]\n'
                            '\n'
                            '        test_result = _segment_result(\n'
                            '            swing_candles=swing_candles,\n'
                            '            income_candles=income_candles,\n'
                            '            dividends=dividends,\n'
                            '            vix_values=vix_values,\n'
                            '            symbol=symbol,\n'
                            '            config=selected_config,\n'
                            '            start_index=test_start,\n'
                            '            end_index=test_end,\n'
                            '        )\n'
                            '        strategy_metrics, strategy_returns = hybrid_metrics(\n'
                            '            test_result\n'
                            '        )\n'
                            '\n'
                            '        test_dates = [\n'
                            '            candle.date\n'
                            '            for candle in swing_candles[test_start:test_end]\n'
                            '        ]\n'
                            '\n'
                            '        try:\n'
                            '            benchmark_bars = [\n'
                            '                adjusted_map[test_date]\n'
                            '                for test_date in test_dates\n'
                            '            ]\n'
                            '        except KeyError as exc:\n'
                            '            raise ValueError(\n'
                            '                f"Benchmark adjusted price is missing for '
                            '{exc.args[0]}."\n'
                            '            ) from exc\n'
                            '\n'
                            '        benchmark = run_buy_and_hold_benchmark(\n'
                            '            bars=benchmark_bars,\n'
                            '            symbol=symbol,\n'
                            '            config=selected_config,\n'
                            '            uses_adjusted_close=(\n'
                            '                benchmark_uses_adjusted_close\n'
                            '            ),\n'
                            '        )\n'
                            '\n'
                            '        observations = len(strategy_returns)\n'
                            '        all_strategy_returns.extend(strategy_returns)\n'
                            '        all_benchmark_returns.extend(benchmark.returns)\n'
                            '        exposure_weighted += (\n'
                            '            strategy_metrics.exposure * observations\n'
                            '        )\n'
                            '        benchmark_exposure_weighted += (\n'
                            '            benchmark.metrics.exposure * observations\n'
                            '        )\n'
                            '        total_observations += observations\n'
                            '\n'
                            '        windows.append(\n'
                            '            WalkForwardWindow(\n'
                            '                number=window_number,\n'
                            '                train_start=swing_candles[\n'
                            '                    train_start\n'
                            '                ].date,\n'
                            '                train_end=swing_candles[\n'
                            '                    train_end - 1\n'
                            '                ].date,\n'
                            '                test_start=swing_candles[\n'
                            '                    test_start\n'
                            '                ].date,\n'
                            '                test_end=swing_candles[\n'
                            '                    test_end - 1\n'
                            '                ].date,\n'
                            '                selected_candidate=best_candidate.name,\n'
                            '                selected_maximum_vix=(\n'
                            '                    best_candidate.maximum_vix_for_entries\n'
                            '                ),\n'
                            '                selected_breakout_volume=(\n'
                            '                    best_candidate.breakout_volume_multiplier\n'
                            '                ),\n'
                            '                training_score=best_score,\n'
                            '                strategy_metrics=strategy_metrics,\n'
                            '                benchmark_metrics=benchmark.metrics,\n'
                            '                strategy_trades=len(test_result.trades),\n'
                            '                strategy_win_rate=test_result.win_rate,\n'
                            '                strategy_profit_factor=(\n'
                            '                    test_result.profit_factor\n'
                            '                ),\n'
                            '                cagr_advantage=(\n'
                            '                    strategy_metrics.cagr\n'
                            '                    - benchmark.metrics.cagr\n'
                            '                ),\n'
                            '            )\n'
                            '        )\n'
                            '\n'
                            '        train_start += step_bars\n'
                            '        window_number += 1\n'
                            '\n'
                            '    if not windows:\n'
                            '        raise ValueError(\n'
                            '            "The selected walk-forward settings produced no '
                            'windows."\n'
                            '        )\n'
                            '\n'
                            '    strategy_exposure = (\n'
                            '        exposure_weighted / total_observations\n'
                            '        if total_observations\n'
                            '        else 0.0\n'
                            '    )\n'
                            '    benchmark_exposure = (\n'
                            '        benchmark_exposure_weighted / total_observations\n'
                            '        if total_observations\n'
                            '        else 0.0\n'
                            '    )\n'
                            '    strategy_overall = metrics_from_returns(\n'
                            '        all_strategy_returns,\n'
                            '        exposure=strategy_exposure,\n'
                            '    )\n'
                            '    benchmark_overall = metrics_from_returns(\n'
                            '        all_benchmark_returns,\n'
                            '        exposure=benchmark_exposure,\n'
                            '    )\n'
                            '\n'
                            '    return WalkForwardResult(\n'
                            '        symbol=symbol.strip().upper(),\n'
                            '        train_bars=train_bars,\n'
                            '        test_bars=test_bars,\n'
                            '        step_bars=step_bars,\n'
                            '        windows=tuple(windows),\n'
                            '        out_of_sample_metrics=strategy_overall,\n'
                            '        benchmark_metrics=benchmark_overall,\n'
                            '        cagr_advantage=(\n'
                            '            strategy_overall.cagr\n'
                            '            - benchmark_overall.cagr\n'
                            '        ),\n'
                            '        positive_alpha_windows=sum(\n'
                            '            1\n'
                            '            for window in windows\n'
                            '            if window.cagr_advantage > 0\n'
                            '        ),\n'
                            '        total_windows=len(windows),\n'
                            '        benchmark_uses_adjusted_close=(\n'
                            '            benchmark_uses_adjusted_close\n'
                            '        ),\n'
                            '    )\n'
                            '\n'
                            '\n'
                            'def format_walk_forward_report(\n'
                            '    result: WalkForwardResult,\n'
                            ') -> str:\n'
                            '    percent = lambda value: f"{value * 100.0:,.2f}%"\n'
                            '    ratio = lambda value: f"{value:,.2f}"\n'
                            '    benchmark_type = (\n'
                            '        "adjusted-close total return"\n'
                            '        if result.benchmark_uses_adjusted_close\n'
                            '        else "price-return fallback"\n'
                            '    )\n'
                            '    strategy = result.out_of_sample_metrics\n'
                            '    benchmark = result.benchmark_metrics\n'
                            '\n'
                            '    lines = [\n'
                            '        "=" * 78,\n'
                            '        "QPX BOT v1.8 — WALK-FORWARD OUT-OF-SAMPLE VALIDATION",\n'
                            '        "=" * 78,\n'
                            '        f"Symbol                    : {result.symbol}",\n'
                            '        f"Training window           : {result.train_bars} bars",\n'
                            '        f"Testing window            : {result.test_bars} bars",\n'
                            '        f"Step size                 : {result.step_bars} bars",\n'
                            '        f"Completed OOS windows     : {result.total_windows}",\n'
                            '        (\n'
                            '            "Positive-alpha windows    : "\n'
                            '            f"{result.positive_alpha_windows}/"\n'
                            '            f"{result.total_windows}"\n'
                            '        ),\n'
                            '        f"Benchmark method          : {benchmark_type}",\n'
                            '        "-" * 78,\n'
                            '        "OUT-OF-SAMPLE AGGREGATE",\n'
                            '        (\n'
                            '            "QPX contribution-adjusted return : "\n'
                            '            f"{percent(strategy.total_return)}"\n'
                            '        ),\n'
                            '        (\n'
                            '            "SPY contribution-adjusted return : "\n'
                            '            f"{percent(benchmark.total_return)}"\n'
                            '        ),\n'
                            '        f"QPX CAGR                         : '
                            '{percent(strategy.cagr)}",\n'
                            '        f"SPY CAGR                         : '
                            '{percent(benchmark.cagr)}",\n'
                            '        f"CAGR advantage                   : '
                            '{percent(result.cagr_advantage)}",\n'
                            '        f"QPX Sharpe                       : '
                            '{ratio(strategy.sharpe_ratio)}",\n'
                            '        f"SPY Sharpe                       : '
                            '{ratio(benchmark.sharpe_ratio)}",\n'
                            '        f"QPX Sortino                      : '
                            '{ratio(strategy.sortino_ratio)}",\n'
                            '        f"SPY Sortino                      : '
                            '{ratio(benchmark.sortino_ratio)}",\n'
                            '        f"QPX maximum drawdown             : '
                            '{percent(strategy.maximum_drawdown)}",\n'
                            '        f"SPY maximum drawdown             : '
                            '{percent(benchmark.maximum_drawdown)}",\n'
                            '        f"QPX swing exposure               : '
                            '{percent(strategy.exposure)}",\n'
                            '        "-" * 78,\n'
                            '        "WINDOWS",\n'
                            '    ]\n'
                            '\n'
                            '    for window in result.windows:\n'
                            '        lines.append(\n'
                            '            (\n'
                            '                f"{window.number:02d} "\n'
                            '                f"train {window.train_start}..{window.train_end} | "\n'
                            '                f"test {window.test_start}..{window.test_end} | "\n'
                            '                f"{window.selected_candidate} | "\n'
                            '                f"QPX CAGR {percent(window.strategy_metrics.cagr)} | '
                            '"\n'
                            '                f"SPY CAGR {percent(window.benchmark_metrics.cagr)} | '
                            '"\n'
                            '                f"alpha {percent(window.cagr_advantage)}"\n'
                            '            )\n'
                            '        )\n'
                            '\n'
                            '    lines.extend(\n'
                            '        [\n'
                            '            "=" * 78,\n'
                            '            (\n'
                            '                "Parameter selection uses training windows only; "\n'
                            '                "reported aggregate metrics use unseen test '
                            'windows."\n'
                            '            ),\n'
                            '            (\n'
                            '                "Research simulation only. Results are not live "\n'
                            '                "trading performance or financial advice."\n'
                            '            ),\n'
                            '        ]\n'
                            '    )\n'
                            '    return "\\n".join(lines)\n'
                            '\n'
                            '\n'
                            'def write_walk_forward_windows(\n'
                            '    result: WalkForwardResult,\n'
                            '    filename: str | Path,\n'
                            ') -> Path:\n'
                            '    path = Path(filename)\n'
                            '    path.parent.mkdir(parents=True, exist_ok=True)\n'
                            '\n'
                            '    with path.open(\n'
                            '        "w",\n'
                            '        newline="",\n'
                            '        encoding="utf-8",\n'
                            '    ) as file:\n'
                            '        writer = csv.writer(file)\n'
                            '        writer.writerow(\n'
                            '            [\n'
                            '                "Window",\n'
                            '                "TrainStart",\n'
                            '                "TrainEnd",\n'
                            '                "TestStart",\n'
                            '                "TestEnd",\n'
                            '                "Candidate",\n'
                            '                "MaximumVIX",\n'
                            '                "BreakoutVolumeMultiplier",\n'
                            '                "TrainingScore",\n'
                            '                "StrategyReturn",\n'
                            '                "StrategyCAGR",\n'
                            '                "StrategySharpe",\n'
                            '                "StrategySortino",\n'
                            '                "StrategyMaxDrawdown",\n'
                            '                "StrategyExposure",\n'
                            '                "BenchmarkReturn",\n'
                            '                "BenchmarkCAGR",\n'
                            '                "BenchmarkSharpe",\n'
                            '                "BenchmarkSortino",\n'
                            '                "BenchmarkMaxDrawdown",\n'
                            '                "CAGRAdvantage",\n'
                            '                "Trades",\n'
                            '                "WinRate",\n'
                            '                "ProfitFactor",\n'
                            '            ]\n'
                            '        )\n'
                            '\n'
                            '        for window in result.windows:\n'
                            '            writer.writerow(\n'
                            '                [\n'
                            '                    window.number,\n'
                            '                    window.train_start.isoformat(),\n'
                            '                    window.train_end.isoformat(),\n'
                            '                    window.test_start.isoformat(),\n'
                            '                    window.test_end.isoformat(),\n'
                            '                    window.selected_candidate,\n'
                            '                    f"{window.selected_maximum_vix:.6f}",\n'
                            '                    f"{window.selected_breakout_volume:.6f}",\n'
                            '                    f"{window.training_score:.10f}",\n'
                            '                    f"{window.strategy_metrics.total_return:.10f}",\n'
                            '                    f"{window.strategy_metrics.cagr:.10f}",\n'
                            '                    f"{window.strategy_metrics.sharpe_ratio:.10f}",\n'
                            '                    f"{window.strategy_metrics.sortino_ratio:.10f}",\n'
                            '                    '
                            'f"{window.strategy_metrics.maximum_drawdown:.10f}",\n'
                            '                    f"{window.strategy_metrics.exposure:.10f}",\n'
                            '                    f"{window.benchmark_metrics.total_return:.10f}",\n'
                            '                    f"{window.benchmark_metrics.cagr:.10f}",\n'
                            '                    f"{window.benchmark_metrics.sharpe_ratio:.10f}",\n'
                            '                    '
                            'f"{window.benchmark_metrics.sortino_ratio:.10f}",\n'
                            '                    '
                            'f"{window.benchmark_metrics.maximum_drawdown:.10f}",\n'
                            '                    f"{window.cagr_advantage:.10f}",\n'
                            '                    window.strategy_trades,\n'
                            '                    f"{window.strategy_win_rate:.10f}",\n'
                            '                    f"{window.strategy_profit_factor:.10f}",\n'
                            '                ]\n'
                            '            )\n'
                            '\n'
                            '    return path\n'
                            '\n'
                            '\n'
                            'def write_walk_forward_json(\n'
                            '    result: WalkForwardResult,\n'
                            '    filename: str | Path,\n'
                            ') -> Path:\n'
                            '    path = Path(filename)\n'
                            '    path.parent.mkdir(parents=True, exist_ok=True)\n'
                            '\n'
                            '    payload = asdict(result)\n'
                            '\n'
                            '    for window in payload["windows"]:\n'
                            '        for key in (\n'
                            '            "train_start",\n'
                            '            "train_end",\n'
                            '            "test_start",\n'
                            '            "test_end",\n'
                            '        ):\n'
                            '            window[key] = window[key].isoformat()\n'
                            '\n'
                            '    path.write_text(\n'
                            '        json.dumps(payload, indent=2),\n'
                            '        encoding="utf-8",\n'
                            '    )\n'
                            '    return path\n',
 'QPX_RUN_WALK_FORWARD.py': '#!/usr/bin/env python3\n'
                            '"""Run QPX walk-forward validation from the real-data folder."""\n'
                            '\n'
                            'from __future__ import annotations\n'
                            '\n'
                            'import argparse\n'
                            'from datetime import datetime, timezone\n'
                            'import json\n'
                            'from pathlib import Path\n'
                            'from typing import Sequence\n'
                            '\n'
                            'from qpx_bot.config import BotConfig\n'
                            'from qpx_bot.dividends import load_dividend_csv\n'
                            'from qpx_bot.performance import load_adjusted_bars\n'
                            'from qpx_bot.real_data import (\n'
                            '    align_vix_to_candles,\n'
                            '    load_market_csv,\n'
                            '    load_vix_csv,\n'
                            '    sha256_file,\n'
                            '    trim_market_history,\n'
                            ')\n'
                            'from qpx_bot.run_real_backtest import (\n'
                            '    DEFAULT_INPUT_DIR,\n'
                            '    required_input_paths,\n'
                            ')\n'
                            'from qpx_bot.validation import validate_real_data\n'
                            'from qpx_bot.walk_forward import (\n'
                            '    format_walk_forward_report,\n'
                            '    run_walk_forward,\n'
                            '    write_walk_forward_json,\n'
                            '    write_walk_forward_windows,\n'
                            ')\n'
                            '\n'
                            '\n'
                            'PROJECT_ROOT = Path(__file__).resolve().parent\n'
                            'DEFAULT_OUTPUT_DIR = (\n'
                            '    PROJECT_ROOT / "reports" / "qpx_walk_forward"\n'
                            ')\n'
                            '\n'
                            '\n'
                            'def _parser() -> argparse.ArgumentParser:\n'
                            '    parser = argparse.ArgumentParser(\n'
                            '        description=(\n'
                            '            "Run rolling QPX training/testing windows and compare "\n'
                            '            "unseen results with adjusted-close SPY buy-and-hold."\n'
                            '        )\n'
                            '    )\n'
                            '    parser.add_argument(\n'
                            '        "--input-dir",\n'
                            '        default=str(DEFAULT_INPUT_DIR),\n'
                            '    )\n'
                            '    parser.add_argument(\n'
                            '        "--output-dir",\n'
                            '        default=str(DEFAULT_OUTPUT_DIR),\n'
                            '    )\n'
                            '    parser.add_argument("--symbol", default="SPY")\n'
                            '    parser.add_argument("--train-bars", type=int, default=252)\n'
                            '    parser.add_argument("--test-bars", type=int, default=63)\n'
                            '    parser.add_argument("--step-bars", type=int, default=63)\n'
                            '    return parser\n'
                            '\n'
                            '\n'
                            'def main(argv: Sequence[str] | None = None) -> int:\n'
                            '    args = _parser().parse_args(argv)\n'
                            '    config = BotConfig()\n'
                            '    paths = required_input_paths(args.input_dir)\n'
                            '    missing = [path for path in paths.values() if not path.exists()]\n'
                            '\n'
                            '    print("=" * 78)\n'
                            '    print("QPX BOT v1.8 — WALK-FORWARD + SPY BENCHMARK RUNNER")\n'
                            '    print("=" * 78)\n'
                            '\n'
                            '    if missing:\n'
                            '        print("Missing real-data inputs:")\n'
                            '        for path in missing:\n'
                            '            print(f"  {path}")\n'
                            '        return 2\n'
                            '\n'
                            '    swing = load_market_csv(paths["swing"])\n'
                            '    income = load_market_csv(paths["income"])\n'
                            '    vix_points = load_vix_csv(paths["vix"])\n'
                            '    dividends = load_dividend_csv(paths["dividends"])\n'
                            '    adjusted_bars, uses_adjusted = load_adjusted_bars(\n'
                            '        paths["swing"]\n'
                            '    )\n'
                            '\n'
                            '    validation = validate_real_data(\n'
                            '        swing_candles=swing,\n'
                            '        income_candles=income,\n'
                            '        vix_points=vix_points,\n'
                            '        dividends=dividends,\n'
                            '        config=config,\n'
                            '    )\n'
                            '\n'
                            '    if not validation.ready:\n'
                            '        print(validation.format_text())\n'
                            '        return 3\n'
                            '\n'
                            '    assert validation.common_start is not None\n'
                            '    assert validation.common_end is not None\n'
                            '\n'
                            '    swing = trim_market_history(\n'
                            '        swing,\n'
                            '        start_date=validation.common_start,\n'
                            '        end_date=validation.common_end,\n'
                            '    )\n'
                            '    income = [\n'
                            '        candle\n'
                            '        for candle in income\n'
                            '        if candle.date <= validation.common_end\n'
                            '    ]\n'
                            '    adjusted_bars = [\n'
                            '        bar\n'
                            '        for bar in adjusted_bars\n'
                            '        if (\n'
                            '            validation.common_start\n'
                            '            <= bar.date\n'
                            '            <= validation.common_end\n'
                            '        )\n'
                            '    ]\n'
                            '    vix_values = align_vix_to_candles(\n'
                            '        swing,\n'
                            '        vix_points,\n'
                            '        maximum_gap_days=7,\n'
                            '    )\n'
                            '\n'
                            '    result = run_walk_forward(\n'
                            '        swing_candles=swing,\n'
                            '        income_candles=income,\n'
                            '        dividends=dividends,\n'
                            '        vix_values=vix_values,\n'
                            '        adjusted_bars=adjusted_bars,\n'
                            '        symbol=args.symbol,\n'
                            '        config=config,\n'
                            '        train_bars=args.train_bars,\n'
                            '        test_bars=args.test_bars,\n'
                            '        step_bars=args.step_bars,\n'
                            '        benchmark_uses_adjusted_close=uses_adjusted,\n'
                            '    )\n'
                            '\n'
                            '    output = Path(args.output_dir).expanduser().resolve()\n'
                            '    output.mkdir(parents=True, exist_ok=True)\n'
                            '\n'
                            '    report_path = output / "walk_forward_report.txt"\n'
                            '    windows_path = output / "walk_forward_windows.csv"\n'
                            '    result_path = output / "walk_forward_result.json"\n'
                            '    manifest_path = output / "walk_forward_manifest.json"\n'
                            '\n'
                            '    report = format_walk_forward_report(result)\n'
                            '    report_path.write_text(report + "\\n", encoding="utf-8")\n'
                            '    write_walk_forward_windows(result, windows_path)\n'
                            '    write_walk_forward_json(result, result_path)\n'
                            '\n'
                            '    manifest = {\n'
                            '        "generated_at_utc": datetime.now(\n'
                            '            timezone.utc\n'
                            '        ).isoformat(),\n'
                            '        "qpx_version": "1.8.0",\n'
                            '        "symbol": args.symbol.strip().upper(),\n'
                            '        "train_bars": args.train_bars,\n'
                            '        "test_bars": args.test_bars,\n'
                            '        "step_bars": args.step_bars,\n'
                            '        "benchmark_adjusted_close": uses_adjusted,\n'
                            '        "inputs": {\n'
                            '            name: {\n'
                            '                "path": str(path),\n'
                            '                "sha256": sha256_file(path),\n'
                            '            }\n'
                            '            for name, path in paths.items()\n'
                            '        },\n'
                            '        "outputs": {\n'
                            '            "report": str(report_path),\n'
                            '            "windows": str(windows_path),\n'
                            '            "result": str(result_path),\n'
                            '        },\n'
                            '    }\n'
                            '    manifest_path.write_text(\n'
                            '        json.dumps(manifest, indent=2),\n'
                            '        encoding="utf-8",\n'
                            '    )\n'
                            '\n'
                            '    print(report)\n'
                            '    print()\n'
                            '    print("Artifacts:")\n'
                            '    for path in (\n'
                            '        report_path,\n'
                            '        windows_path,\n'
                            '        result_path,\n'
                            '        manifest_path,\n'
                            '    ):\n'
                            '        print(f"  {path}")\n'
                            '\n'
                            '    print()\n'
                            '    print("=" * 78)\n'
                            '    print("QPX WALK-FORWARD VALIDATION: COMPLETE")\n'
                            '    print("=" * 78)\n'
                            '    return 0\n'
                            '\n'
                            '\n'
                            'if __name__ == "__main__":\n'
                            '    raise SystemExit(main())\n',
 'tests/test_qpx_bot_walk_forward.py': 'from dataclasses import replace\n'
                                       'from datetime import date, timedelta\n'
                                       'from pathlib import Path\n'
                                       'from tempfile import TemporaryDirectory\n'
                                       '\n'
                                       'from qpx_bot.config import BotConfig\n'
                                       'from qpx_bot.data_loader import Candle\n'
                                       'from qpx_bot.dividends import DividendEvent\n'
                                       'from qpx_bot.performance import AdjustedBar\n'
                                       'from qpx_bot.walk_forward import (\n'
                                       '    Candidate,\n'
                                       '    format_walk_forward_report,\n'
                                       '    run_walk_forward,\n'
                                       '    write_walk_forward_json,\n'
                                       '    write_walk_forward_windows,\n'
                                       ')\n'
                                       '\n'
                                       '\n'
                                       'config = replace(\n'
                                       '    BotConfig(),\n'
                                       '    starting_cash=10_000.0,\n'
                                       '    monthly_contribution=500.0,\n'
                                       '    ema_fast_period=2,\n'
                                       '    ema_slow_period=3,\n'
                                       '    rsi_period=3,\n'
                                       '    rmi_period=3,\n'
                                       '    rmi_momentum=2,\n'
                                       '    sma_trend_period=5,\n'
                                       '    sma_slope_lookback=2,\n'
                                       '    atr_period=3,\n'
                                       '    average_volume_period=3,\n'
                                       '    breakout_lookback=3,\n'
                                       '    minimum_average_daily_volume=1_000,\n'
                                       ')\n'
                                       '\n'
                                       'start = date(2022, 1, 3)\n'
                                       'swing = []\n'
                                       'income = []\n'
                                       'adjusted = []\n'
                                       '\n'
                                       'for index in range(360):\n'
                                       '    day = start + timedelta(days=index)\n'
                                       '    swing_price = 100.0 + (index * 0.08)\n'
                                       '    income_price = 40.0 + (index * 0.03)\n'
                                       '\n'
                                       '    swing.append(\n'
                                       '        Candle(\n'
                                       '            date=day,\n'
                                       '            open=swing_price,\n'
                                       '            high=swing_price + 1.0,\n'
                                       '            low=swing_price - 1.0,\n'
                                       '            close=swing_price + 0.20,\n'
                                       '            volume=3_000_000,\n'
                                       '        )\n'
                                       '    )\n'
                                       '    income.append(\n'
                                       '        Candle(\n'
                                       '            date=day,\n'
                                       '            open=income_price,\n'
                                       '            high=income_price + 0.50,\n'
                                       '            low=income_price - 0.50,\n'
                                       '            close=income_price + 0.10,\n'
                                       '            volume=1_500_000,\n'
                                       '        )\n'
                                       '    )\n'
                                       '    adjusted.append(\n'
                                       '        AdjustedBar(\n'
                                       '            date=day,\n'
                                       '            open=swing_price,\n'
                                       '            close=swing_price + 0.20,\n'
                                       '            adjusted_close=(\n'
                                       '                swing_price\n'
                                       '                + 0.20\n'
                                       '                + (index * 0.01)\n'
                                       '            ),\n'
                                       '        )\n'
                                       '    )\n'
                                       '\n'
                                       'dividends = [\n'
                                       '    DividendEvent(\n'
                                       '        date=swing[index].date,\n'
                                       '        amount_per_share=0.20,\n'
                                       '    )\n'
                                       '    for index in (30, 90, 150, 210, 270, 330)\n'
                                       ']\n'
                                       'vix = [20.0] * len(swing)\n'
                                       'candidates = (\n'
                                       '    Candidate("LOW_VIX", 18.0, 1.20),\n'
                                       '    Candidate("BASE_VIX", 28.0, 1.20),\n'
                                       ')\n'
                                       '\n'
                                       'result = run_walk_forward(\n'
                                       '    swing_candles=swing,\n'
                                       '    income_candles=income,\n'
                                       '    dividends=dividends,\n'
                                       '    vix_values=vix,\n'
                                       '    adjusted_bars=adjusted,\n'
                                       '    symbol="TEST",\n'
                                       '    config=config,\n'
                                       '    train_bars=120,\n'
                                       '    test_bars=40,\n'
                                       '    step_bars=40,\n'
                                       '    candidates=candidates,\n'
                                       ')\n'
                                       '\n'
                                       'assert result.total_windows == 6\n'
                                       'assert len(result.windows) == 6\n'
                                       'assert (\n'
                                       '    result.out_of_sample_metrics.observation_count\n'
                                       '    == 240\n'
                                       ')\n'
                                       'assert result.benchmark_metrics.exposure == 1.0\n'
                                       'assert result.benchmark_uses_adjusted_close\n'
                                       'assert result.windows[0].test_start > '
                                       'result.windows[0].train_end\n'
                                       'assert (\n'
                                       '    "WALK-FORWARD OUT-OF-SAMPLE VALIDATION"\n'
                                       '    in format_walk_forward_report(result)\n'
                                       ')\n'
                                       '\n'
                                       'with TemporaryDirectory() as temporary_directory:\n'
                                       '    directory = Path(temporary_directory)\n'
                                       '    windows = write_walk_forward_windows(\n'
                                       '        result,\n'
                                       '        directory / "windows.csv",\n'
                                       '    )\n'
                                       '    payload = write_walk_forward_json(\n'
                                       '        result,\n'
                                       '        directory / "result.json",\n'
                                       '    )\n'
                                       '\n'
                                       '    assert windows.exists()\n'
                                       '    assert payload.exists()\n'
                                       '    assert "CAGRAdvantage" in '
                                       'windows.read_text(encoding="utf-8")\n'
                                       '    assert \'"total_windows": 6\' in payload.read_text(\n'
                                       '        encoding="utf-8"\n'
                                       '    )\n'
                                       '\n'
                                       'print("QPX Bot Walk-Forward Validation PASS")\n',
 'qpx_bot/data_inputs/WALK_FORWARD_README.txt': 'QPX WALK-FORWARD VALIDATION\n'
                                                '===========================\n'
                                                '\n'
                                                'Run from the QPX_ALPHA project root:\n'
                                                '\n'
                                                'python QPX_RUN_WALK_FORWARD.py --symbol SPY\n'
                                                '\n'
                                                'Default validation design:\n'
                                                '\n'
                                                '- 252 daily bars for parameter selection\n'
                                                '- 63 unseen daily bars for out-of-sample testing\n'
                                                '- 63-bar step size, producing non-overlapping '
                                                'test windows\n'
                                                '- A declared three-choice VIX-entry grid\n'
                                                '- Adjusted-close SPY total-return buy-and-hold '
                                                'benchmark\n'
                                                '- Identical starting cash and monthly '
                                                'contribution schedule\n'
                                                '- Contribution-adjusted time-weighted returns\n'
                                                '- CAGR, volatility, Sharpe, Sortino, drawdown, '
                                                'and exposure\n'
                                                '- Per-window and aggregate out-of-sample reports\n'
                                                '\n'
                                                'Outputs:\n'
                                                '\n'
                                                'reports/qpx_walk_forward/walk_forward_report.txt\n'
                                                'reports/qpx_walk_forward/walk_forward_windows.csv\n'
                                                'reports/qpx_walk_forward/walk_forward_result.json\n'
                                                'reports/qpx_walk_forward/walk_forward_manifest.json\n'
                                                '\n'
                                                'Raw downloaded data and generated reports are '
                                                'excluded from Git.\n'
                                                '\n'
                                                'Walk-forward results are historical research '
                                                'only. They are not live\n'
                                                'performance, a guarantee, or financial advice.\n'}
PATCHES = {'qpx_bot/hybrid.py': [('    forced_entry_indices: set[int] | None = None,\n'
                        ') -> HybridBacktestResult:',
                        '    forced_entry_indices: set[int] | None = None,\n'
                        '    start_trading_index: int = 0,\n'
                        ') -> HybridBacktestResult:'),
                       ('    if len(swing_candles) < 2:\n'
                        '        raise ValueError("At least two swing candles are required.")\n',
                        '    if len(swing_candles) < 2:\n'
                        '        raise ValueError("At least two swing candles are required.")\n'
                        '\n'
                        '    if not 0 <= start_trading_index < len(swing_candles):\n'
                        '        raise ValueError("Start trading index is outside the candle '
                        'series.")\n'),
                       ('    first_swing_date = swing_candles[0].date',
                        '    first_swing_date = (\n'
                        '        swing_candles[start_trading_index].date\n'
                        '    )'),
                       ('    for index, swing_candle in enumerate(swing_candles):',
                        '    for index in range(\n'
                        '        start_trading_index,\n'
                        '        len(swing_candles),\n'
                        '    ):\n'
                        '        swing_candle = swing_candles[index]'),
                       ('        start_date=swing_candles[0].date,',
                        '        start_date=swing_candles[\n'
                        '            start_trading_index\n'
                        '        ].date,')],
 'qpx_bot/yahoo_data.py': [('    close: float\n    volume: int',
                            '    close: float\n    adjusted_close: float\n    volume: int'),
                           ('    closes = _sequence(quote, "close")\n'
                            '    volumes = _sequence(quote, "volume")',
                            '    closes = _sequence(quote, "close")\n'
                            '    volumes = _sequence(quote, "volume")\n'
                            '    adjusted_groups = indicators.get("adjclose")\n'
                            '    adjusted_closes: Sequence[Any] = ()\n'
                            '\n'
                            '    if (\n'
                            '        isinstance(adjusted_groups, list)\n'
                            '        and adjusted_groups\n'
                            '        and isinstance(adjusted_groups[0], Mapping)\n'
                            '    ):\n'
                            '        adjusted_closes = _sequence(\n'
                            '            adjusted_groups[0],\n'
                            '            "adjclose",\n'
                            '        )'),
                           ('        volume_value = (\n'
                            '            volumes[index]\n'
                            '            if index < len(volumes)\n'
                            '            and volumes[index] is not None\n'
                            '            else 0\n'
                            '        )',
                            '        volume_value = (\n'
                            '            volumes[index]\n'
                            '            if index < len(volumes)\n'
                            '            and volumes[index] is not None\n'
                            '            else 0\n'
                            '        )\n'
                            '        adjusted_value = (\n'
                            '            adjusted_closes[index]\n'
                            '            if index < len(adjusted_closes)\n'
                            '            and adjusted_closes[index] is not None\n'
                            '            else close_price\n'
                            '        )'),
                           ('            close=float(close_price),\n'
                            '            volume=max(0, int(float(volume_value))),',
                            '            close=float(close_price),\n'
                            '            adjusted_close=float(adjusted_value),\n'
                            '            volume=max(0, int(float(volume_value))),'),
                           ('        if row.open <= 0 or row.close <= 0:',
                            '        if (\n'
                            '            row.open <= 0\n'
                            '            or row.close <= 0\n'
                            '            or row.adjusted_close <= 0\n'
                            '        ):'),
                           ('        ("Date", "Open", "High", "Low", "Close", "Volume"),',
                            '        (\n'
                            '            "Date",\n'
                            '            "Open",\n'
                            '            "High",\n'
                            '            "Low",\n'
                            '            "Close",\n'
                            '            "AdjClose",\n'
                            '            "Volume",\n'
                            '        ),'),
                           ('                f"{row.close:.8f}",\n                row.volume,',
                            '                f"{row.close:.8f}",\n'
                            '                f"{row.adjusted_close:.8f}",\n'
                            '                row.volume,'),
                           ('AppleWebKit/537.36 QPXBot/1.7', 'AppleWebKit/537.36 QPXBot/1.8')],
 'qpx_bot/run_real_backtest.py': [('"qpx_version": "1.7.0"', '"qpx_version": "1.8.0"'),
                                  ('QPX BOT v1.7 — REAL HISTORICAL DATA RUNNER',
                                   'QPX BOT v1.8 — REAL HISTORICAL DATA RUNNER')],
 'tests/test_qpx_bot_real_data.py': [('"qpx_version": "1.7.0"', '"qpx_version": "1.8.0"')],
 'QPX_FETCH_AND_RUN_REAL_DATA.py': [('QPX BOT v1.7 — MARKET DATA ACQUISITION + REAL BACKTEST',
                                     'QPX BOT v1.8 — MARKET DATA ACQUISITION + REAL BACKTEST')]}
TARGET_PATHS = [*FILES, *PATCHES]
committed_state: dict[str, bytes | None] = {}


def run(command: list[str]) -> None:
    print("$ " + " ".join(command))
    subprocess.run(command, cwd=ROOT, check=True)


def head_bytes(relative: str) -> bytes | None:
    completed = subprocess.run(
        ["git", "show", f"HEAD:{relative}"],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    return (
        completed.stdout
        if completed.returncode == 0
        else None
    )


def desired_bytes(content: str) -> bytes:
    return (
        textwrap.dedent(content).strip() + "\n"
    ).encode("utf-8")


def is_staged(relative: str) -> bool:
    return subprocess.run(
        ["git", "diff", "--cached", "--quiet", "--", relative],
        cwd=ROOT,
    ).returncode != 0


def fully_patched(
    text: str,
    replacements: list[tuple[str, str]],
) -> bool:
    return all(new in text for _, new in replacements)


def ensure_patch_targets_are_safe() -> None:
    """
    Protect existing committed engine files.

    The six FILES entries are deliberately overwritten because the
    terminal transcript confirms V1 created those exact partial files
    before failing. Existing engine files in PATCHES remain protected.
    """
    unsafe: list[str] = []

    for relative in TARGET_PATHS:
        if is_staged(relative):
            unsafe.append(relative)
            continue

        if relative in FILES:
            continue

        path = ROOT / relative
        committed = head_bytes(relative)
        current = path.read_bytes() if path.exists() else None

        if committed is None:
            unsafe.append(relative)
            continue

        if current == committed:
            continue

        if current is not None:
            try:
                text = current.decode("utf-8")
            except UnicodeDecodeError:
                unsafe.append(relative)
                continue

            if fully_patched(text, PATCHES[relative]):
                continue

        unsafe.append(relative)

    if unsafe:
        raise RuntimeError(
            "These existing engine files contain unrelated local "
            "edits and were not overwritten:\n"
            + "\n".join(unsafe)
        )


def snapshot_head_state() -> None:
    for relative in TARGET_PATHS:
        committed_state[relative] = head_bytes(relative)

        current_path = ROOT / relative
        if current_path.exists():
            backup_path = BACKUP / relative
            backup_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(current_path, backup_path)


def install_static_files() -> None:
    for relative, content in FILES.items():
        path = ROOT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(desired_bytes(content))
        print(f"Installed: {relative}")


def patch_from_committed_head() -> None:
    for relative, replacements in PATCHES.items():
        original = committed_state.get(relative)

        if original is None:
            raise FileNotFoundError(
                f"Required committed file was not found: {relative}"
            )

        content = original.decode("utf-8")

        for old, new in replacements:
            if old in content:
                content = content.replace(old, new, 1)
            elif new in content:
                continue
            else:
                raise RuntimeError(
                    f"Expected source marker was not found in "
                    f"{relative}:\n{old}"
                )

        path = ROOT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Updated: {relative}")


def restore_head_state() -> None:
    print("Restoring every target to committed HEAD...")

    for relative, original in committed_state.items():
        path = ROOT / relative

        if original is None:
            if path.exists():
                path.unlink()
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(original)


def commit_and_push() -> None:
    paths = list(TARGET_PATHS)

    try:
        paths.append(
            str(Path(__file__).resolve().relative_to(ROOT))
        )
    except ValueError:
        pass

    run(["git", "add", "--", *paths])

    staged = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        cwd=ROOT,
    )

    if staged.returncode == 0:
        print("Walk-forward validation is already committed.")
        return

    run([
        "git",
        "commit",
        "-m",
        "Implement QPX Bot walk-forward benchmark validation",
    ])

    branch = subprocess.check_output(
        ["git", "branch", "--show-current"],
        cwd=ROOT,
        text=True,
    ).strip()

    if not branch:
        raise RuntimeError("Cannot push from detached Git state.")

    run(["git", "push", "origin", branch])


def main() -> int:
    print("=" * 78)
    print("QPX BOT — WALK-FORWARD VALIDATION INSTALLER V3")
    print("=" * 78)
    print(f"Project: {ROOT}")

    ensure_patch_targets_are_safe()
    snapshot_head_state()

    try:
        install_static_files()
        patch_from_committed_head()
        run([sys.executable, "tests/run_all_tests.py"])
    except Exception:
        restore_head_state()
        raise

    commit_and_push()

    print()
    print("Refreshing SPY/QDTE/VIX files with adjusted close...")
    print()

    try:
        run([
            sys.executable,
            "QPX_FETCH_AND_RUN_REAL_DATA.py",
            "--symbol",
            "SPY",
            "--download-only",
        ])
        run([
            sys.executable,
            "QPX_RUN_WALK_FORWARD.py",
            "--symbol",
            "SPY",
        ])
    except Exception:
        print()
        print("=" * 78)
        print("QPX WALK-FORWARD CODE: INSTALLED AND PUSHED")
        print("LIVE DATA/VALIDATION RUN: NEEDS RETRY")
        print("=" * 78)
        print(
            "Re-run:\n"
            "python QPX_FETCH_AND_RUN_REAL_DATA.py "
            "--symbol SPY --download-only && "
            "python QPX_RUN_WALK_FORWARD.py --symbol SPY"
        )
        return 2

    print()
    print("=" * 78)
    print("QPX WALK-FORWARD + BENCHMARK VALIDATION: COMPLETE")
    print("=" * 78)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
