"""
Generator Engine

Uses BuilderEngine to generate common project assets.
"""

from tools.builder_engine import BuilderEngine


class GeneratorEngine:

    def __init__(self):
        self.builder = BuilderEngine()

    def generate_module(self, name):

        self.builder.write(
            f"app/{name.lower()}.py",
            f"""
\"\"
{name} Module
Generated by QPX_ALPHA
\"\"

class {name}:
    pass
"""
        )

    def generate_service(self, name):

        self.builder.write(
            f"core/services/{name.lower()}_service.py",
            f"""
\"\"
{name} Service
Generated by QPX_ALPHA
\"\"

class {name}Service:
    pass
"""
        )

    def generate_package(self, name):

        self.builder.write(
            f"{name}/__init__.py",
            '# Package generated by QPX_ALPHA'
        )

    def generate_test(self, name):

        self.builder.write(
            f"tests/test_{name.lower()}.py",
            f"""
def test_{name.lower()}():
    print(\"PASS\")
"""
        )

    def generate_readme(self, name):

        self.builder.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by QPX_ALPHA."
        )

    def generate_config(self, name):

        self.builder.write(
            f"config/{name.lower()}.cfg",
            "# Generated configuration"
        )

    def generate_plugin(self, name):

        self.builder.write(
            f"plugins/{name.lower()}.py",
            f"""
def initialize():
    print(\"{name} initialized\")
"""
        )

    def generate_adr(self, title):

        safe = title.lower().replace(" ", "_")

        self.builder.write(
            f"docs/adr/{safe}.md",
            f"# ADR\n\n{title}"
        )
